# Generated by Django 4.2.1 on 2023-06-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(blank=True, default=None, null=True)),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Prueba3')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Prueba3')),
            ],
        ),
    ]
