# Generated by Django 4.1.2 on 2023-06-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(max_length=5)),
                ('precio', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Revistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('articulo', models.IntegerField(max_length=5)),
                ('mes', models.CharField(max_length=50)),
                ('stock', models.IntegerField(max_length=10)),
                ('precio', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.CharField(max_length=20)),
                ('precio', models.IntegerField(max_length=6)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
    ]
