# Generated by Django 4.1.2 on 2023-06-26 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CaosNews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarios',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='diarios',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='revistas',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='revistas',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='revistas',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='suscripcion',
            name='precio',
        ),
    ]
