# Generated by Django 4.1.2 on 2023-06-26 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CaosNews', '0002_remove_diarios_precio_remove_diarios_stock_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diarios',
            new_name='Diario',
        ),
        migrations.RenameModel(
            old_name='Revistas',
            new_name='Revista',
        ),
    ]
