# Generated by Django 4.1.2 on 2023-06-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaosNews', '0003_rename_diarios_diario_rename_revistas_revista'),
    ]

    operations = [
        migrations.AddField(
            model_name='diario',
            name='precio',
            field=models.IntegerField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diario',
            name='stock',
            field=models.IntegerField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revista',
            name='articulo',
            field=models.IntegerField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revista',
            name='precio',
            field=models.IntegerField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revista',
            name='stock',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='precio',
            field=models.IntegerField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
