# Generated by Django 4.1.2 on 2023-06-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaosNews', '0004_diario_precio_diario_stock_revista_articulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diario',
            name='dia',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diario',
            name='foto',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revista',
            name='foto',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diario',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diario',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='revista',
            name='articulo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='revista',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='revista',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
