# Generated by Django 4.1.2 on 2023-06-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaosNews', '0005_diario_dia_diario_foto_revista_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='dia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='revista',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
