# Generated by Django 4.1.2 on 2023-06-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaosNews', '0006_alter_diario_dia_alter_diario_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='bastian_vasquez_alexander_pulgar'),
        ),
        migrations.AlterField(
            model_name='revista',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='bastian_vasquez_alexander_pulgar'),
        ),
    ]
