# Generated by Django 4.1.2 on 2023-06-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaosNews', '0007_alter_diario_foto_alter_revista_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='dia',
            field=models.DateField(null=True),
        ),
    ]
