# Generated by Django 4.1.2 on 2023-06-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaosNews', '0010_alter_diario_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='dia',
            field=models.DateField(),
        ),
    ]
