# Generated by Django 4.1.2 on 2023-06-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaosNews', '0012_alter_diario_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='dia',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
