# Generated by Django 4.1.2 on 2023-06-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CaosNews', '0013_alter_diario_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diario',
            name='dia',
        ),
    ]
