# Generated by Django 4.1.2 on 2023-06-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaosNews', '0014_remove_diario_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='diario',
            name='dia',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
