nombre=str(input("ingrese nopmbre del alumno"))
n1=float(input("ingrese primera nota"))
n2=float(input("ingrese segunda nota"))
n3=float(input("ingrese tercera nota"))
ne=float(input("ingrese nota examen"))
prom=(n1*0.30+n2*0.35+n3*0.35)
print(nombre, "tiene un promedio de", prom)
nf=(prom*0.60+ne*0.40)
print("el estudiante termina con una nota final de", nf)
